### ISSUE TITLE
Performance Hack

### ISSUE THREAD

**Issue by ybur-yug** [benfred/bens-blog-code#4]
Hey Ben,

So I was perusing your blog entry/the code involved and I was struck by how you handle sparse matrices.

Your performance hack is quite clever and works with the situation given, but in the circumstance I have actually personally found a (somewhat trivial) fix that involves the core Numpy/Scipy libraries involved with linear algebra.

Due to the inherent nature of sparse matrix multiplication within the libraries dot product functions of large matrices (specifically with regard to cosine similarity, the exact case I have applied the following technique to) there is a much more efficient method that actually yields the entire calculation.

The core issue is that these methods per the libraries' base definitions are C-Contiguous rather than F-Contiguous. Fortran is light years faster than C at any linalg process you can throw at it with the appropriate libraries.

In an applied, only dot-product system I utilized this method and wrote on it
https://medium.com/@_devbob/from-0-to-warp-speed-b780a2bc36ce

However, after I published this facebook polished a much more robust method that utilized Intel's entire kernel math lib to override standard BLAS libraries. I cannot find the post now (it may have been removed for whatever reason) but I will search my bookmarks and see if I can provide you with it tomorrow sometime (its quite late here)

Anywho, not a huge thing but it was quite literally a 1000x speedup on the operations w.r.t sparse matrix cosine similarity specifically.

Cheers,
Bobby

**Comment by ybur-yug** [comment]
For reference the screen in the article mentioned was utilizing a several gigabyte, VERY deep, VERY sparse matrix, and it was repeated to perform that the level mentioned (1000x speedup) through the simple optimization in the article, rather than having to patch everything w/intel kernel math libs. So it appears its a quite similar use-case.

**Comment by benfred** [comment]
Awesome! thanks for the link - I'll have to check it out!

One difference is that I'm multiplying lots of tiny sparse matrices here (I have one for each artist - rather than have each artist as a row in a larger matrix).  This means that checking the sizes takes a large amount of the time relative to the actual dot product - hence the hack.

The only reason I'm doing it pairwise is to make the code in the blog simpler to understand for casual people reading the post.  It would be much faster to generate all the distances at once in a big matrix multiply,  and then applying the method you wrote about to make it even faster

thanks again
