### ISSUE TITLE
Question on BM25

### ISSUE THREAD

**Issue by BrianMiner** [benfred/bens-blog-code#6]
Great blog posts! I had one confusion I hope you dont mind being asked here. 

I have calculated BM25 distance for a query against documents to get a **score** for each query / document pair. Is that what you are doing with the BM25 weighting function? Like https://en.wikipedia.org/wiki/Okapi_BM25?

You then use the weighting it appears in a cosine distance - which confused me because I thought BM25 was itself a distance score?

**Comment by benfred** [comment]
The version of bm25 in that wikipedia link weights the document by bm25 - but leaves the query unweighted (gives a weight of 1 for each word in the query, then sums it up). This is ok for text search because the query strings are short.

The 'query' in that post is long though: we're treating users as the terms and then the query is every single user in the artist we're looking at. In this case it makes sense to weight the query as well. 
So to get bm25 distance we weight both the query and the document, and then take the dot product to sum up the weighted terms (note: its not cosine distance, which would involve dividing the dot product by their length norms)

This book https://mitpress.mit.edu/books/information-retrieval has more details in chapter 8 iirc.
