### ISSUE TITLE
Approximate ALS: Initialization time

### ISSUE THREAD

**Issue by chapleau** [benfred/bens-blog-code#9]
This is a very nice blog post, thanks! From what I understand reading the code, the times here exclude the initialization time of the different ANN methods, right ? I had the impression that NMSLIB's "weakness", so to speak, was that building up the initial graphs could be quite lengthy. Would your conclusions change if you were to include the initialization time on a very big dataset (millions of users and/or items) ?

**Comment by benfred** [comment]
thanks!

The times do exclude the index build time - and the index build time is much faster for faiss/annoy than it is for nmslib in most cases. This hasn't been a deal breaker for me, but its probably worth pointing out a bit more.

If you're worried about indexing time - I would suggest not using the 'post=2' parameter in the HNSW index. It roughly doubles the indexing time, and while it helps the querying - it probably isn't worth it in this case.

I updated the script here that calculates the best batch query times here: https://github.com/benfred/bens-blog-code/commit/68cab6467dffac191dbbe52826ab0dab99b6f6ba . I changed to include the index time in the graph, and to add the fastest set of parameters for hnsw with post=0 (with more than 99% recall on this test ).

The indexing time looks like : 
![lastfm50indextime](https://user-images.githubusercontent.com/69536/32300268-f7168b30-bf15-11e7-807a-2bac1151ebe6.png).

If you include indexing time, Faiss is the best option in this case (15 seconds indexing time and 7.5 seconds total query time for all items). For comparison HNSW is 40 seconds indexing and 1.2 seconds query time with the post=0 option.

Having said that - it really depends on your dataset. Its pretty common to have many more users than items - so query speed would be more important than index speed in that case. Also with the lastfm.py example in my implicit library, nmslib is still the fastest (since the querying is single threaded).

I updated the README for these scripts to include the graphs in that commit
